# frozen_string_literal: true

moscow = Station.new('Moscow')
sochi = Station.new('Sochi')
new_york = Station.new('New York')

railway.stations_list.push(moscow, sochi, new_york)

route1 = Route.new(moscow, sochi)
route2 = Route.new(moscow, new_york)
route3 = Route.new(sochi, new_york)
route4 = Route.new(sochi, moscow)
route5 = Route.new(new_york, sochi)
route6 = Route.new(new_york, moscow)

passenger_train1 = PassengerTrain.new('00024')
passenger_train2 = PassengerTrain.new('sf3-23')
passenger_train3 = PassengerTrain.new('asdas')
passenger_train4 = PassengerTrain.new('65432')
passenger_train5 = PassengerTrain.new('asf-l3')
passenger_train6 = PassengerTrain.new('1df-ac')

passenger_boxcar1 = PassengerBoxcar.new(1, 100)
passenger_boxcar2 = PassengerBoxcar.new(2, 50)
passenger_boxcar3 = PassengerBoxcar.new(3, 167)
passenger_boxcar4 = PassengerBoxcar.new(4, 37)
passenger_boxcar5 = PassengerBoxcar.new(5, 93)
passenger_boxcar6 = PassengerBoxcar.new(6, 36)
passenger_boxcar7 = PassengerBoxcar.new(7, 12)
passenger_boxcar8 = PassengerBoxcar.new(8, 53)
passenger_boxcar9 = PassengerBoxcar.new(9, 112)
passenger_boxcar10 = PassengerBoxcar.new(10, 214)
passenger_boxcar11 = PassengerBoxcar.new(11, 43)
passenger_boxcar12 = PassengerBoxcar.new(12, 46)

passenger_train1.add_boxcar(passenger_boxcar1)
passenger_train1.add_boxcar(passenger_boxcar2)
passenger_train2.add_boxcar(passenger_boxcar3)
passenger_train2.add_boxcar(passenger_boxcar4)
passenger_train3.add_boxcar(passenger_boxcar5)
passenger_train3.add_boxcar(passenger_boxcar6)
passenger_train4.add_boxcar(passenger_boxcar7)
passenger_train4.add_boxcar(passenger_boxcar8)
passenger_train5.add_boxcar(passenger_boxcar9)
passenger_train5.add_boxcar(passenger_boxcar10)
passenger_train6.add_boxcar(passenger_boxcar11)
passenger_train6.add_boxcar(passenger_boxcar12)

passenger_train1.add_route(route1)
passenger_train2.add_route(route2)
passenger_train3.add_route(route3)
passenger_train4.add_route(route4)
passenger_train5.add_route(route5)
passenger_train6.add_route(route6)

cargo_train1 = CargoTrain.new('asd-g3')
cargo_train2 = CargoTrain.new('a35fd')
cargo_train3 = CargoTrain.new('83g-35')
cargo_train4 = CargoTrain.new('29934')
cargo_train5 = CargoTrain.new('23f-gf')
cargo_train6 = CargoTrain.new('dgg-53')

cargo_boxcar1 = CargoBoxcar.new(1, 1500)
cargo_boxcar2 = CargoBoxcar.new(2, 2700)
cargo_boxcar3 = CargoBoxcar.new(3, 2442)
cargo_boxcar4 = CargoBoxcar.new(4, 1899)
cargo_boxcar5 = CargoBoxcar.new(5, 1304)
cargo_boxcar6 = CargoBoxcar.new(6, 3000)
cargo_boxcar7 = CargoBoxcar.new(7, 1690)
cargo_boxcar8 = CargoBoxcar.new(8, 1997)
cargo_boxcar9 = CargoBoxcar.new(9, 1454)
cargo_boxcar10 = CargoBoxcar.new(10, 3435)
cargo_boxcar11 = CargoBoxcar.new(11, 2463)
cargo_boxcar12 = CargoBoxcar.new(12, 1879)

cargo_train1.add_boxcar(cargo_boxcar1)
cargo_train1.add_boxcar(cargo_boxcar2)
cargo_train2.add_boxcar(cargo_boxcar3)
cargo_train2.add_boxcar(cargo_boxcar4)
cargo_train3.add_boxcar(cargo_boxcar5)
cargo_train3.add_boxcar(cargo_boxcar6)
cargo_train4.add_boxcar(cargo_boxcar7)
cargo_train4.add_boxcar(cargo_boxcar8)
cargo_train5.add_boxcar(cargo_boxcar9)
cargo_train5.add_boxcar(cargo_boxcar10)
cargo_train6.add_boxcar(cargo_boxcar11)
cargo_train6.add_boxcar(cargo_boxcar12)

cargo_train1.add_route(route1)
cargo_train2.add_route(route2)
cargo_train3.add_route(route3)
cargo_train4.add_route(route4)
cargo_train5.add_route(route5)
cargo_train6.add_route(route6)

railway.stations_list.each do |station|
  puts "#{station.name}:"
  station.trains.each { |train| puts "№#{train.number} #{train.class} #{train.boxcars.count}" }
end
